version: "3.8"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.docker
    networks:
      - docker-network
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.docker
    networks:
      - docker-network
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - docker-network
    volumes:
      - mongodb-vol:/data/mydb

networks:
  docker-network:
    driver: bridge

volumes:
  mongodb-vol:
    driver: local