apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
  namespace: mern-devops
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: atkaridarshan04/bookstore-frontend:v1
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_BACKEND_URL
              value: http://backend:8000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mern-devops
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
      nodePort: 31000